CREATE TABLE `llm_conversation_references` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID，数据库自增，唯一标识每条引用记录',
  `user_id` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户ID，标识哪个用户发起了这次抓取任务，支持多用户环境',
  `job_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务ID，标识生成QA对抓取AI平台内容的任务，一个job_id对应一批对话',
  `conversation_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '对话ID（外键），关联到llm_conversations表的conversation_id，建立一对多关系',
  `platform` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台名称：deepseek, doubao, qianwen, kimi, yuanbao',
  `brand` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '品牌，例如：阿里巴巴、腾讯、字节跳动等',
  `category` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品大类',
  `keyword` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '生成question的关键词，用户提交job时系统会根据关键词生成question',
  `query_content` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户查询内容，完整的用户提问内容',
  `url` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '引用链接URL，完整的引用链接地址，用于追溯信息来源',
  `domain` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '域名，从URL中提取的域名，如news.cn, zol.com.cn，用于域名分析和统计',
  `content_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内容类型：news, tech_review, gov_report等，标识链接内容的性质和可信度',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间，记录引用链接入库时间，用于数据管理',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间，记录引用信息最后修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_conversation_url` (`conversation_id`,`url`(255)),
  KEY `idx_user_job` (`user_id`,`job_id`),
  KEY `idx_platform` (`platform`),
  KEY `idx_keyword` (`keyword`),
  KEY `idx_domain` (`domain`),
  KEY `idx_content_type` (`content_type`),
  KEY `idx_conversation_id_fix` (`conversation_id`),
  CONSTRAINT `llm_conversation_references_ibfk_1` FOREIGN KEY (`conversation_id`) REFERENCES `llm_conversations` (`conversation_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='存储对话中引用链接的关联表'

CREATE TABLE `llm_conversations` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID，数据库自增，唯一标识每条对话记录',
  `user_id` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户ID，标识哪个用户发起了这次抓取任务，支持多用户环境',
  `job_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务ID，标识生成QA对抓取AI平台内容的任务，一个job_id对应一批对话',
  `conversation_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '对话唯一标识，通常是文件名中的唯一标识符，确保每个对话的唯一性',
  `platform` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台名称：deepseek, doubao, qianwen, kimi, yuanbao',
  `brand` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '品牌，例如：阿里巴巴、腾讯、字节跳动等',
  `category` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品大类',
  `keyword` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '生成question的关键词，用户提交job时系统会根据关键词生成question',
  `query_content` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户查询内容，完整的用户提问内容',
  `answer_content` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'AI回答内容，AI生成的完整回答',
  `model_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '抓取AI平台内容时使用的模型名称，如Kwaipilot/KAT-Dev，记录生成回答使用的具体模型',
  `token_usage` int(11) DEFAULT NULL COMMENT 'token使用量，记录这次对话消耗的token数量，用于成本分析',
  `extracted_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '文件生成时间（来自文件的Generated at），原始文件创建时间，保持数据时序一致性',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据库记录创建时间，数据入库时间，用于数据管理',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间，记录最后修改时间，支持数据审计',
  PRIMARY KEY (`id`),
  UNIQUE KEY `conversation_id` (`conversation_id`),
  KEY `idx_user_job` (`user_id`,`job_id`),
  KEY `idx_conversation_id` (`conversation_id`),
  KEY `idx_platform` (`platform`),
  KEY `idx_keyword` (`keyword`),
  KEY `idx_extracted_at` (`extracted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='存储LLM对话内容的主表'

CREATE TABLE `qa_brand_state` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment primary key',
  `date` date NOT NULL COMMENT 'Date of the record',
  `user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户ID，标识哪个用户发起了这次抓取任务，支持多用户环境',
  `job_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务ID，标识生成QA对抓取AI平台内容的任务，一个job_id对应一批对话',
  `conversation_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '对话唯一标识，通常是文件名中的唯一标识符，确保每个对话的唯一性',
  `brand` varchar(100) NOT NULL COMMENT 'Brand name mentioned',
  `category` varchar(64) NOT NULL COMMENT '商品大类',
  `platform` varchar(100) NOT NULL COMMENT 'Platform where the question was posted (e.g., Qwen, Deepseek, etc.)',
  `keyword` varchar(100) NOT NULL COMMENT '生成question的关键词，用户提交job时系统会根据关键词生成question',
  `is_mentioned` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the brand is mentioned in the answer (0 = no, 1 = yes)',
  `is_first_mention` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the brand is the first mentioned in the answer',
  `sentiment_status` varchar(20) NOT NULL COMMENT 'Sentiment/emotion status (e.g., positive, negative, neutral)',
  `brands_found` json DEFAULT NULL COMMENT 'All brands found in the text (e.g., ["海尔 (Haier)", ...])',
  PRIMARY KEY (`id`),
  KEY `idx_date` (`date`),
  KEY `idx_brand` (`brand`),
  KEY `idx_platform` (`platform`),
  KEY `idx_sentiment_status` (`sentiment_status`),
  KEY `idx_conversation_id` (`conversation_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_job_id` (`job_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COMMENT='Records of brand status in Q&A'

CREATE TABLE `qa_reference` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID，数据库自增，唯一标识每条引用记录',
  `user_id` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户ID，标识哪个用户发起了这次抓取任务，支持多用户环境',
  `job_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务ID，标识生成QA对抓取AI平台内容的任务，一个job_id对应一批对话',
  `conversation_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '对话ID，标识单次AI对话的唯一ID，一个conversation_id对应一条对话的引用链接',
  `platform` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台名称',
  `brand` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '品牌，例如：阿里巴巴、腾讯、字节跳动等',
  `category` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品大类',
  `keyword` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '生成question的关键词，用户提交job时系统会根据关键词生成question',
  `query_content` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户查询内容，完整的用户提问内容',
  `url` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '引用链接URL，完整的引用链接地址，用于追溯信息来源',
  `is_published_link` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为发稿链接：0-否（默认），1-是；标识该URL是否为自媒体发布的稿件链接，若AI平台读取的链接与发稿链接一致则标记为1',
  `domain` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '域名，从URL中提取的域名，如news.cn, zol.com.cn，用于域名分析和统计',
  `content_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内容类型：news, tech_review, gov_report等，标识链接内容的性质和可信度',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间，记录引用链接入库时间，用于数据管理',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间，记录引用信息最后修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_conversation_url` (`conversation_id`,`url`(191)),
  KEY `idx_user_job` (`user_id`,`job_id`),
  KEY `idx_platform` (`platform`),
  KEY `idx_keyword` (`keyword`),
  KEY `idx_domain` (`domain`),
  KEY `idx_content_type` (`content_type`),
  KEY `idx_is_published_link` (`is_published_link`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='存储对话中引用链接的关联表'
