-- Phase 4.1: add collection lifecycle model.
-- Depends on Phase 3.1 monitoring project tables and the existing executors table.
-- Safe to rerun: every table uses CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS `collection_jobs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `tenant_key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Tenant key',
  `collection_job_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Stable collection job id',
  `project_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Monitoring project id',
  `prompt_set_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Prompt set id used by this run',
  `source_job_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Legacy llm_query_jobs job_id during compatibility period',
  `status` enum('pending','running','succeeded','failed','expired','cancelled') NOT NULL DEFAULT 'pending' COMMENT 'Collection job status',
  `window_start` timestamp NULL DEFAULT NULL COMMENT 'Collection window start',
  `window_end` timestamp NULL DEFAULT NULL COMMENT 'Collection window end',
  `expected_task_count` int(11) NOT NULL DEFAULT '0' COMMENT 'Expected task count',
  `succeeded_task_count` int(11) NOT NULL DEFAULT '0' COMMENT 'Succeeded task count',
  `failed_task_count` int(11) NOT NULL DEFAULT '0' COMMENT 'Failed task count',
  `created_by` bigint(20) DEFAULT NULL COMMENT 'Creator user id',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_collection_job` (`tenant_key`,`collection_job_id`),
  KEY `idx_collection_jobs_tenant_project_status` (`tenant_key`,`project_id`,`status`),
  KEY `idx_collection_jobs_prompt_set` (`tenant_key`,`prompt_set_id`),
  KEY `idx_collection_jobs_source_job` (`tenant_key`,`source_job_id`),
  CONSTRAINT `collection_jobs_ibfk_tenant` FOREIGN KEY (`tenant_key`) REFERENCES `tenants` (`tenant_key`) ON DELETE CASCADE,
  CONSTRAINT `collection_jobs_ibfk_project` FOREIGN KEY (`tenant_key`,`project_id`) REFERENCES `monitoring_projects` (`tenant_key`,`project_id`),
  CONSTRAINT `collection_jobs_ibfk_prompt_set` FOREIGN KEY (`tenant_key`,`prompt_set_id`) REFERENCES `prompt_sets` (`tenant_key`,`prompt_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Collection job batches';

CREATE TABLE IF NOT EXISTS `collection_tasks` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `tenant_key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Tenant key',
  `collection_task_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Stable collection task id',
  `collection_job_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Collection job id',
  `project_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Monitoring project id',
  `prompt_set_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Prompt set id',
  `prompt_item_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Prompt item id',
  `platform` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'AI platform',
  `query_content` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Prompt content',
  `run_index` int(11) NOT NULL DEFAULT '1' COMMENT 'Run index inside the collection job',
  `status` enum('pending','reserved','running','succeeded','failed','expired','cancelled') NOT NULL DEFAULT 'pending' COMMENT 'Collection task status',
  `lease_owner` varchar(128) DEFAULT NULL COMMENT 'Executor holding the current lease',
  `lease_until` timestamp NULL DEFAULT NULL COMMENT 'Lease expiry time',
  `reserved_at` timestamp NULL DEFAULT NULL COMMENT 'Reserved time',
  `started_at` timestamp NULL DEFAULT NULL COMMENT 'Started time',
  `finished_at` timestamp NULL DEFAULT NULL COMMENT 'Finished time',
  `attempt_count` int(11) NOT NULL DEFAULT '0' COMMENT 'Attempt count',
  `max_attempts` int(11) NOT NULL DEFAULT '3' COMMENT 'Max attempts before terminal failure',
  `last_error_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Last error code',
  `last_error_message` text COLLATE utf8mb4_unicode_ci COMMENT 'Last error message',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_collection_task` (`tenant_key`,`collection_task_id`),
  KEY `idx_collection_tasks_fetch` (`tenant_key`,`status`,`lease_until`,`id`),
  KEY `idx_collection_tasks_job_status` (`tenant_key`,`collection_job_id`,`status`),
  KEY `idx_collection_tasks_project` (`tenant_key`,`project_id`,`status`),
  KEY `idx_collection_tasks_prompt` (`tenant_key`,`prompt_set_id`,`prompt_item_id`),
  KEY `idx_collection_tasks_lease_owner` (`lease_owner`,`status`,`tenant_key`),
  CONSTRAINT `collection_tasks_ibfk_job` FOREIGN KEY (`tenant_key`,`collection_job_id`) REFERENCES `collection_jobs` (`tenant_key`,`collection_job_id`) ON DELETE CASCADE,
  CONSTRAINT `collection_tasks_ibfk_project` FOREIGN KEY (`tenant_key`,`project_id`) REFERENCES `monitoring_projects` (`tenant_key`,`project_id`),
  CONSTRAINT `collection_tasks_ibfk_prompt_item` FOREIGN KEY (`tenant_key`,`prompt_set_id`,`prompt_item_id`) REFERENCES `prompt_items` (`tenant_key`,`prompt_set_id`,`prompt_item_id`),
  CONSTRAINT `collection_tasks_ibfk_executor` FOREIGN KEY (`lease_owner`) REFERENCES `executors` (`executor_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Collection tasks';

CREATE TABLE IF NOT EXISTS `collection_attempts` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `tenant_key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Tenant key',
  `attempt_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Stable attempt id',
  `collection_task_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Collection task id',
  `executor_id` varchar(128) DEFAULT NULL COMMENT 'Executor id',
  `status` enum('running','succeeded','failed','timeout','cancelled') NOT NULL DEFAULT 'running' COMMENT 'Attempt status',
  `started_at` timestamp NULL DEFAULT NULL COMMENT 'Started time',
  `finished_at` timestamp NULL DEFAULT NULL COMMENT 'Finished time',
  `error_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Error code',
  `error_message` text COLLATE utf8mb4_unicode_ci COMMENT 'Error message',
  `raw_response_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Raw response id or external artifact id',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_collection_attempt` (`tenant_key`,`attempt_id`),
  KEY `idx_collection_attempts_task` (`tenant_key`,`collection_task_id`),
  KEY `idx_collection_attempts_executor_status` (`tenant_key`,`executor_id`,`status`),
  KEY `idx_collection_attempts_executor_fk` (`executor_id`),
  CONSTRAINT `collection_attempts_ibfk_task` FOREIGN KEY (`tenant_key`,`collection_task_id`) REFERENCES `collection_tasks` (`tenant_key`,`collection_task_id`) ON DELETE CASCADE,
  CONSTRAINT `collection_attempts_ibfk_executor` FOREIGN KEY (`executor_id`) REFERENCES `executors` (`executor_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Collection execution attempts';
